---
langs: [fr_FR]
baseurl: "/"
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
 - jekyll-paginate
 - jekyll-seo-tag
exclude:
 - nbproject
plugins:
 - jekyll-seo-tag
title: "Documentation plugin Scan.Ip"
description: "Ceci est la documentation, li√©e au plugin Scan.Ip pour Jeedom."
author: "Ynats"
image: https://www.jeedom.com/site/logo.png
social:
  name:  Jeedom-Scan.Ip
  links:
    - https://github.com/Ynats/jeedom-plugin-scan.ip
    - https://github.com/jeedom